// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppliedToGroups implements AppliedToGroupInterface
type FakeAppliedToGroups struct {
	Fake *FakeControlplaneV1beta2
}

var appliedtogroupsResource = schema.GroupVersionResource{Group: "controlplane.antrea.tanzu.vmware.com", Version: "v1beta2", Resource: "appliedtogroups"}

var appliedtogroupsKind = schema.GroupVersionKind{Group: "controlplane.antrea.tanzu.vmware.com", Version: "v1beta2", Kind: "AppliedToGroup"}

// Get takes name of the appliedToGroup, and returns the corresponding appliedToGroup object, and an error if there is any.
func (c *FakeAppliedToGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.AppliedToGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(appliedtogroupsResource, name), &v1beta2.AppliedToGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.AppliedToGroup), err
}

// List takes label and field selectors, and returns the list of AppliedToGroups that match those selectors.
func (c *FakeAppliedToGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.AppliedToGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(appliedtogroupsResource, appliedtogroupsKind, opts), &v1beta2.AppliedToGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.AppliedToGroupList{ListMeta: obj.(*v1beta2.AppliedToGroupList).ListMeta}
	for _, item := range obj.(*v1beta2.AppliedToGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appliedToGroups.
func (c *FakeAppliedToGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(appliedtogroupsResource, opts))
}

// Create takes the representation of a appliedToGroup and creates it.  Returns the server's representation of the appliedToGroup, and an error, if there is any.
func (c *FakeAppliedToGroups) Create(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.CreateOptions) (result *v1beta2.AppliedToGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(appliedtogroupsResource, appliedToGroup), &v1beta2.AppliedToGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.AppliedToGroup), err
}

// Update takes the representation of a appliedToGroup and updates it. Returns the server's representation of the appliedToGroup, and an error, if there is any.
func (c *FakeAppliedToGroups) Update(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.UpdateOptions) (result *v1beta2.AppliedToGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(appliedtogroupsResource, appliedToGroup), &v1beta2.AppliedToGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.AppliedToGroup), err
}

// Delete takes name of the appliedToGroup and deletes it. Returns an error if one occurs.
func (c *FakeAppliedToGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(appliedtogroupsResource, name), &v1beta2.AppliedToGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppliedToGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(appliedtogroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta2.AppliedToGroupList{})
	return err
}

// Patch applies the patch and returns the patched appliedToGroup.
func (c *FakeAppliedToGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.AppliedToGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(appliedtogroupsResource, name, pt, data, subresources...), &v1beta2.AppliedToGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.AppliedToGroup), err
}
