// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/antrea/pkg/apis/stats/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkPolicyLister helps list NetworkPolicies.
type AntreaNetworkPolicyStatsLister interface {
	// List lists all NetworkPolicies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.AntreaNetworkPolicyStats, err error)
	// NetworkPolicies returns an object that can list and get NetworkPolicies.
	AntreaNetworkPolicyStats(namespace string) AntreaNetworkPolicyStatsNamespaceLister
}

// networkPolicyLister implements the NetworkPolicyLister interface.
type antreawNetworkPolicyStatsLister struct {
	indexer cache.Indexer
}

// NewNetworkPolicyLister returns a new NetworkPolicyLister.
func NewAntreaNetworkPolicyStatsLister(indexer cache.Indexer) AntreaNetworkPolicyStatsLister {
	return &antreawNetworkPolicyStatsLister{indexer: indexer}
}

// List lists all NetworkPolicies in the indexer.
func (s *antreawNetworkPolicyStatsLister) List(selector labels.Selector) (ret []*v1alpha1.AntreaNetworkPolicyStats, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AntreaNetworkPolicyStats))
	})
	return ret, err
}

// NetworkPolicies returns an object that can list and get NetworkPolicies.
func (s *antreawNetworkPolicyStatsLister) AntreaNetworkPolicyStats(namespace string) AntreaNetworkPolicyStatsNamespaceLister {
	return antreaNetworkPolicyStatsNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkPolicyNamespaceLister helps list and get NetworkPolicies.
type AntreaNetworkPolicyStatsNamespaceLister interface {
	// List lists all NetworkPolicies in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.AntreaNetworkPolicyStats, err error)
	// Get retrieves the NetworkPolicy from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.AntreaNetworkPolicyStats, error)
}

// networkPolicyNamespaceLister implements the NetworkPolicyNamespaceLister
// interface.
type antreaNetworkPolicyStatsNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkPolicies in the indexer for a given namespace.
func (s antreaNetworkPolicyStatsNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AntreaNetworkPolicyStats, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AntreaNetworkPolicyStats))
	})
	return ret, err
}

// Get retrieves the NetworkPolicy from the indexer for a given namespace and name.
func (s antreaNetworkPolicyStatsNamespaceLister) Get(name string) (*v1alpha1.AntreaNetworkPolicyStats, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("networkpolicystats"), name)
	}
	return obj.(*v1alpha1.AntreaNetworkPolicyStats), nil
}
