// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressPolicies implements EgressPolicyInterface
type FakeEgressPolicies struct {
	Fake *FakeControlplaneV1beta1
	ns   string
}

var egresspoliciesResource = schema.GroupVersionResource{Group: "controlplane.antrea.tanzu.vmware.com", Version: "v1beta1", Resource: "egresspolicies"}

var egresspoliciesKind = schema.GroupVersionKind{Group: "controlplane.antrea.tanzu.vmware.com", Version: "v1beta1", Kind: "EgressPolicy"}

// Get takes name of the egressPolicy, and returns the corresponding egressPolicy object, and an error if there is any.
func (c *FakeEgressPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EgressPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(egresspoliciesResource, c.ns, name), &v1beta1.EgressPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.EgressPolicy), err
}

// Watch returns a watch.Interface that watches the requested egressPolicies.
func (c *FakeEgressPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(egresspoliciesResource, c.ns, opts))

}
