// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1beta2"
	scheme "github.com/vmware-tanzu/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppliedToGroupsGetter has a method to return a AppliedToGroupInterface.
// A group's client should implement this interface.
type AppliedToGroupsGetter interface {
	AppliedToGroups() AppliedToGroupInterface
}

// AppliedToGroupInterface has methods to work with AppliedToGroup resources.
type AppliedToGroupInterface interface {
	Create(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.CreateOptions) (*v1beta2.AppliedToGroup, error)
	Update(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.UpdateOptions) (*v1beta2.AppliedToGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.AppliedToGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.AppliedToGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.AppliedToGroup, err error)
	AppliedToGroupExpansion
}

// appliedToGroups implements AppliedToGroupInterface
type appliedToGroups struct {
	client rest.Interface
}

// newAppliedToGroups returns a AppliedToGroups
func newAppliedToGroups(c *ControlplaneV1beta2Client) *appliedToGroups {
	return &appliedToGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the appliedToGroup, and returns the corresponding appliedToGroup object, and an error if there is any.
func (c *appliedToGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.AppliedToGroup, err error) {
	result = &v1beta2.AppliedToGroup{}
	err = c.client.Get().
		Resource("appliedtogroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppliedToGroups that match those selectors.
func (c *appliedToGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.AppliedToGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.AppliedToGroupList{}
	err = c.client.Get().
		Resource("appliedtogroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appliedToGroups.
func (c *appliedToGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("appliedtogroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a appliedToGroup and creates it.  Returns the server's representation of the appliedToGroup, and an error, if there is any.
func (c *appliedToGroups) Create(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.CreateOptions) (result *v1beta2.AppliedToGroup, err error) {
	result = &v1beta2.AppliedToGroup{}
	err = c.client.Post().
		Resource("appliedtogroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appliedToGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a appliedToGroup and updates it. Returns the server's representation of the appliedToGroup, and an error, if there is any.
func (c *appliedToGroups) Update(ctx context.Context, appliedToGroup *v1beta2.AppliedToGroup, opts v1.UpdateOptions) (result *v1beta2.AppliedToGroup, err error) {
	result = &v1beta2.AppliedToGroup{}
	err = c.client.Put().
		Resource("appliedtogroups").
		Name(appliedToGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(appliedToGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the appliedToGroup and deletes it. Returns an error if one occurs.
func (c *appliedToGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("appliedtogroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appliedToGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("appliedtogroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched appliedToGroup.
func (c *appliedToGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.AppliedToGroup, err error) {
	result = &v1beta2.AppliedToGroup{}
	err = c.client.Patch(pt).
		Resource("appliedtogroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
