// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/antrea/pkg/apis/security/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EgressPolicyLister helps list EgressPolicies.
type EgressPolicyLister interface {
	// List lists all EgressPolicies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.EgressPolicy, err error)
	// EgressPolicies returns an object that can list and get EgressPolicies.
	EgressPolicies(namespace string) EgressPolicyNamespaceLister
	EgressPolicyListerExpansion
}

// egressPolicyLister implements the EgressPolicyLister interface.
type egressPolicyLister struct {
	indexer cache.Indexer
}

// NewEgressPolicyLister returns a new EgressPolicyLister.
func NewEgressPolicyLister(indexer cache.Indexer) EgressPolicyLister {
	return &egressPolicyLister{indexer: indexer}
}

// List lists all EgressPolicies in the indexer.
func (s *egressPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.EgressPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EgressPolicy))
	})
	return ret, err
}

// EgressPolicies returns an object that can list and get EgressPolicies.
func (s *egressPolicyLister) EgressPolicies(namespace string) EgressPolicyNamespaceLister {
	return egressPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// EgressPolicyNamespaceLister helps list and get EgressPolicies.
type EgressPolicyNamespaceLister interface {
	// List lists all EgressPolicies in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.EgressPolicy, err error)
	// Get retrieves the EgressPolicy from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.EgressPolicy, error)
	EgressPolicyNamespaceListerExpansion
}

// egressPolicyNamespaceLister implements the EgressPolicyNamespaceLister
// interface.
type egressPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all EgressPolicies in the indexer for a given namespace.
func (s egressPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.EgressPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EgressPolicy))
	})
	return ret, err
}

// Get retrieves the EgressPolicy from the indexer for a given namespace and name.
func (s egressPolicyNamespaceLister) Get(name string) (*v1alpha1.EgressPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("egresspolicy"), name)
	}
	return obj.(*v1alpha1.EgressPolicy), nil
}
