// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1beta1"
	scheme "github.com/vmware-tanzu/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressPoliciesGetter has a method to return a EgressPolicyInterface.
// A group's client should implement this interface.
type EgressPoliciesGetter interface {
	EgressPolicies(namespace string) EgressPolicyInterface
}

// EgressPolicyInterface has methods to work with EgressPolicy resources.
type EgressPolicyInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.EgressPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.EgressPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	EgressPolicyExpansion
}

// egressPolicies implements EgressPolicyInterface
type egressPolicies struct {
	client rest.Interface
	ns     string
}

// newEgressPolicies returns a EgressPolicies
func newEgressPolicies(c *ControlplaneV1beta1Client, namespace string) *egressPolicies {
	return &egressPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the egressPolicy, and returns the corresponding egressPolicy object, and an error if there is any.
func (c *egressPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.EgressPolicy, err error) {
	result = &v1beta1.EgressPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egresspolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressPolicies that match those selectors.
func (c *egressPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.EgressPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.EgressPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egresspolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressPolicies.
func (c *egressPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("egresspolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}
